-*- coding: cp1251 -*-
http://www.ica-chernikov.fmi.npu.edu.ua/
* International Conference on Algebra (ICA)
dedicated to 100th anniversary of S.M. Chernikov
** General information

International Conference on Algebra is dedicated to 100th anniversary of S.M. Chernikov. The conference will be held on August 20-26, 2012 at Dragomanov National Pedagogical University (Kiev, Ukraine).

The conference is organized by

    Dragomanov National Pedagogical University
    Institute of Mathematics of National Academy of Sciences of Ukraine
    Kyiv National Taras Shevchenko University

The working languages of the conference are English (preferable), Ukrainian and Russian.
 

Deadlines

The deadline for registration is 1 May, 2012, for abstract submission is 1 May, 2012.

** Sections

The conference will cover a wide range of research areas.

    Group Theory
    Semigroups and Quasigroups
    Rings, Modules, Representations
    Algebraic Geometry and Number Theory
    Applied Algebra


** Special invited lectures:

     R.Grigorchuk
     K.Gupta
     E.Golod
     H.Heineken
     V.Mazurov
     B.Novikov
     A.Olshanski
     B.Plotkin
     L.Shemetkov
     V.Sushchanski.


** Committees
Programme committee

Yu. Drozd (chairman), O. Artemovych, M. Chernikov, I. Eremin, E. Golod, R.Grigorchuk, K. Gupta, H. Heineken, V. Kirichenko, M. Komarnitsky, L. Kurdachenko, F. Lyman, A. Makhnev, V. Mazurov, B. Novikov, A. Olshanski, B. Plotkin, I. Protasov, V. Remeslennikov, D. Robinson, L. Shemetkov, L. Shevrin, V. Sushchanski, Ya. Sysak, A. Tushev
Organizing committee

V. Andrushchenko (chairman), M. Pratsiovytyi (co-chairman), A. Petravchuk (co-chairman), M. Semko, O. Artemovych, F. Lyman, D. Trebenko, O. Trebenko, I.Raevskaya, M.Raevskaya, R. Nikiforov

** Contact

All questions concerning the conference should be addressed to
email: ica-chernikov@npu.edu.ua

 

Institute of Physics and Mathematics
National Pedagogical Dragomanov University
9 Pyrogova
01030 Kyiv
Ukraine

* Tezy
[[file:d:/Lapack/doct.tex][Статья DFS]]
[[file:~/My%20Documents/Downloads/AbstracLugansk_8.pdf][AbstracLugansk_8.pdf]]
[[file:~/My%20Documents/Downloads/AbstracKharkov_7.pdf][AbstracKharkov_7.pdf]]
1. Conjugacy of piecewise-linear spheric-transitive automorphisms

Let us build a sequence of automorphisms x^(n) on spheric-transitive automorphism in the following way: ...

Proof 
According to induction and theorem 1.1: ... 

Definition
We shall define function ... in the following manner - if all the states of the n-th level of automorphism a are linear functions... otherwise, the value ... is undefined.

Lemma 1.3 If an automorphism ... is piecewise-linear, then ... such, that the value of the function ... is defined.

Theorem 1.4 Piecewise-linear functions a and b are conjugate in ... if and only if ...

Theorem 1.5 Piecewise-linear functions a and b are not conjugate in ... if and only if ...

Remark According to the theorem about differentiable finite-state automorphisms, theorems 1.4 and 1.5 are the conjugacy criteria of such automorphisms.
