Denis178
* Геометрия
** Не решенные
*** Квадраты из спичек	Геометрические задачи 		Вес: 1		Симпатии решивших: 91%		29.11.2009
Из спичек выложена фигура, показанная на рисунке. Переложите 2 спички так, чтобы получилось 4 одинаковых квадрата. Каждая спичка должна быть частью квадрата.

Комментарии: 	 100	| ответить на задачу	  

*** Треугольники из спичек	Геометрические задачи 		Вес: 1		Симпатии решивших: 89%		29.11.2006
Есть 6 спичек. Сложите из них фигуру, состоящую только из четырех равносторонних треугольников. Ломать спички нельзя. Не должно остаться свободных концов спичек.

Комментарии: 	 83	| ответить на задачу	  

*** Прогулка по земному шару	Геометрические задачи 		Вес: 2		Симпатии решивших: 96%		27.11.2006
Мегамозг прошел одну милю на юг, одну милю на восток и одну милю на север и оказался в том месте, откуда отправлялся в путь. Где такое могло случиться?

Комментарии: 	 99	| ответить на задачу	  

*** Минное поле	Геометрические задачи 		Вес: 2		Симпатии решивших: 93%		03.05.2008
Близится наступление оккупантов. Известно, что оккупанты пройдут через поле сусликов. Главному мегамозгу приснилось, что для того, чтобы погибло максимальное число оккупантов, нужно расположить мины на десяти прямых по три штуки на каждой прямой. Но мин у мегамозгов всего 9. Как им расположить мины на поле?

Комментарии: 	 65	| ответить на задачу	  

*** Треугольнутая фигура	Геометрические задачи 		Вес: 2		Симпатии решивших: 78%		03.08.2010
Нарисуйте фигуру, которую можно разрезать как на 3, так и на 4 равных треугольника.

Комментарии: 	 26	| ответить на задачу	  

*** Построить квадрат	Геометрические задачи 		Вес: 3		Симпатии решивших: 95%		11.12.2009
Как построить квадрат с помощью очень длинной односторонней линейки с 2 метками? (Примечания: Такая линейка позволяет проводить только прямые и откладывать заданный отрезок. Сторона построенного квадрата может быть произвольной.)

Комментарии: 	 48	| ответить на задачу	  

*** Развертка куба	Геометрические задачи 		Вес: 3		Симпатии решивших: 94%		13.12.2008
Как из квадрата бумаги 3х3 вырезать фигуру, представляющую собой развертку полной поверхности единичного куба?

Комментарии: 	 48	| ответить на задачу	  

Пилим куб	Геометрические задачи 		Вес: 3		Симпатии решивших: 91%		08.12.2006
За какое минимальное количество распилов можно распилить куб 3×3×3 на составные кубики 1×1×1? Каждый распил может проходить через несколько уже отпиленных кусков. Минимальность обосновать.

Комментарии: 	 25	| ответить на задачу	  

*** Тетрис	Геометрические задачи 		Вес: 3		Симпатии решивших: 90%		26.02.2012
Минимозгу нужно решить три уравнения: соединить детали так, чтобы по обе стороны знака равенства были одинаковые фигуры. Детали можно вращать и отображать зеркально. Помогите ему справиться с заданием.

Комментарии: 	 47	| ответить на задачу	  

*** Треугольники из спичек — 2	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		19.02.2009
Как из 6 спичек сложить 1 равносторонний и 3 равнобедренных (не равносторонних) треугольника? Не ломать. Нельзя накладывать одну спичку на другую. Не должно остаться свободных концов спичек.

Комментарии: 	 69	| ответить на задачу	  

*** Третья проекция	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		29.12.2010
Даны две проекции предмета (см. рисунок). Нарисуйте третью проекцию, при условии что предмет объемный, цельный и все его грани плоские. Приведите не менее четырех вариантов решения.

Комментарии: 	 49	| ответить на задачу	  

*** Разрезание параллелограмма	Геометрические задачи 		Вес: 4		Симпатии решивших: 95%		25.04.2007
Как разрезать параллелограмм на 9 равнобедренных треугольников?

Комментарии: 	 68	| ответить на задачу	  

*** Флаг	Геометрические задачи 		Вес: 4		Симпатии решивших: 94%		14.03.2008
На двуцветном прямоугольном флаге страны Мозголяндии всегда было 14 одинаковых по ширине полосок чередующихся цветов — по полосе на каждого из местных мегамозгов. Вчера правительство соседней Мозголии приняло решение о натурализации двух мегамозгов из Мозголяндии, и они получили новое гражданство. Оказалось, что материал, из которого делали флаг Мозголяндии, больше не производят, сам флаг старый и хлипкий и поэтому его нельзя разрезать больше чем на две части, а традицию надо соблюсти. Что делать мозголяндцам, среди которых стало на два мегамозга меньше, если теперь им нужен прямоугольный флаг с 12-ю полосками максимальной площади?

Комментарии: 	 56	| ответить на задачу	  

*** Четыре коня	Геометрические задачи 		Вес: 4		Симпатии решивших: 89%		27.11.2008
Есть обычная шахматная доска, на которой стоят по главной диагонали 4 коня (поля h1, g2, f3, е4). Требуется разделить доску на 4 равные, одинаковые по форме части таким образом, чтобы в каждой было по одному коню. Каждая часть должна быть связной (состоять из одного куска).

Комментарии: 	 46	| ответить на задачу	  

*** Разрезать круг	Геометрические задачи 		Вес: 4		Симпатии решивших: 89%		14.12.2009
Разрежьте круг на несколько равных (совпадающих при наложении) частей так, чтобы центр круга не лежал на границе хотя бы одной из них.

Комментарии: 	 45	| ответить на задачу	  

*** Дремучий лес	Геометрические задачи 		Вес: 4		Симпатии решивших: 87%		22.08.2009
Мегамозг находится в дремучем лесу, который по площади занимает ровно 100 км2. Форма леса неизвестна, но лес сплошной, без полян. Мегамозг хочет выбраться из леса, пройдя минимально возможное расстояние. Путь какой минимальной длины (и формы) гарантирует, что удастся найти границу леса?

Комментарии: 	 41	| ответить на задачу	  

Разрезать квадрат	Геометрические задачи 		Вес: 4		Симпатии решивших: 82%		19.10.2009
Разрезать квадрат на минимальное число остроугольных треугольников. Доказательство минимальности не требуется.

Комментарии: 	 31	| ответить на задачу	  

*** Телефонный кабель	Геометрические задачи 		Вес: 5		Симпатии решивших: 96%		14.05.2008
Мегамозг работал телефонистом, и однажды ему позвонил диспетчер из офиса и попросил найти закопанный кабель. Кабель был проложен на небольшой глубине по прямой, проходящей ровно в 5 км от той точки, где находился Мегамозг. К сожалению, связь прервалась и диспетчер не успел уточнить, в каком направлении проходит кабель. У Мегамозга есть металлоискатель, который звенит точно над кабелем. Может ли он спланировать свой путь так, чтобы гарантированно найти кабель, пройдя при этом не более 32 км?

Комментарии: 	 74	| ответить на задачу	  

*** Храм	Геометрические задачи 		Вес: 5		Симпатии решивших: 94%		04.10.2011
Вызвал к себе король придворного архитектора, и дал ему задание: "Построй мне храм, и чтобы была в нем лишь одна комната. Стены в ней пусть будут зеркальными, а углов не будет вовсе. Хочу, чтобы она освещалась единственной свечкой, но и неосвещенное место должно остаться." Как архитектору справиться с поставленной задачей?

Комментарии: 	 64	| ответить на задачу	  

*** Луч в кубе	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		13.02.2008
Луч света, направленный из вершины куба, отразившись 2008 раз от его внутренних зеркальных стенок (по закону «угол падения равен углу отражения») и не попадая при этом на ребра, заканчивает свой путь в другой вершине куба. Какое наименьшее расстояние может пройти луч света, если длина ребра куба равна 1?

Комментарии: 	 37	| ответить на задачу	  

*** Мегамозг и яблоко	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		16.08.2008
Однажды Мегамозг шел по улице и увидел плачущего мальчика с яблоком. «Что ты плачешь, мальчик?» — спросил Мегамозг. — «Да вот, яблоко червивое попалось». — «Ничего страшного, — сказал Мегамозг. — Радиус яблока 40 мм, а червяк прогрыз сквозной путь длиной не более 79 мм, и поэтому я сейчас разрежу твое яблоко на два полушария так, что одно из полушарий не будет червивым». Верно ли, что Мегамозг всегда сможет это сделать?
Примечание: яблоко разрезается плоскостью, проходящей через центр; размерами червяка пренебречь.

Комментарии: 	 50	| ответить на задачу	  

*** Рациональный тетраэдр	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		07.10.2009
Можно ли в декартовой системе координат расположить правильный тетраэдр так, чтобы все его вершины лежали в точках с целочисленными координатами?

Комментарии: 	 26	| ответить на задачу	  

*** Внутренняя граница	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		19.12.2011
Мозголяндия имеет форму правильного треугольника. Внутренняя граница делит ее на два равных по площади штата. Опишите форму и расположение границы, если известно, что она непрерывна и имеет минимально возможную длину.

Комментарии: 	 17	| ответить на задачу	  

*** Лачуга в междуречье	Геометрические задачи 		Вес: 5		Симпатии решивших: 92%		06.07.2009
Приток при впадении в реку образует острый угол. На суше, внутри угла, стоит лачуга Мегамозга. Каждый день Мегамозг выходит из нее, идет к притоку, встречает рассвет, затем отправляется к реке, встречает закат и возвращается в лачугу. Как нужно Мегамозгу проложить маршрут, чтобы путь, проходимый им каждый день, был минимален? Считать берега реки и притока прямыми линиями.

Комментарии: 	 44	| ответить на задачу	  

*** Телефонный кабель — 2	Геометрические задачи 		Вес: 5		Симпатии решивших: 92%		26.08.2009
У Мегамозга есть квадратный участок земли со стороной 1 км. Он случайно узнал, что подлые оккупанты тайно проложили телефонный кабель под его участком и используют его для своих грязных оккупантских целей. Кабель прямой и лежит на небольшой глубине (за пределами участка Мегамозга кабель идёт на той же самой глубине и по той же самой прямой на много километров в обе стороны). Узнав об этой подлости, Мегамозг схватил лопату и... задумался. Какой минимальной длины (и какой формы) нужно прокопать траншею, чтобы наверняка найти кабель? Траншея не обязательно должна состоять из связных кусков, она может быть разрывная. Доказательство минимальности не требуется.

Комментарии: 	 35	| ответить на задачу	  

*** Треугольный торт	Геометрические задачи 		Вес: 5		Симпатии решивших: 91%		26.02.2009
Торт имеет форму произвольного треугольника. Два мегамозга делят его следующим образом: первый указывает на торте точку, второй проводит через эту точку прямолинейный разрез и забирает себе большую часть. Какую наибольшую часть торта может обеспечить себе первый мегамозг? Считается, что торт всюду имеет одинаковую толщину.

Комментарии: 	 25	| ответить на задачу

**** Решение

*** Нарисуй ломаную	Геометрические задачи 		Вес: 5		Симпатии решивших: 89%		27.12.2011
На плоскости нарисовано конечное число непересекающихся отрезков. Разрешается соединять свободные концы любых двух отрезков третьим отрезком. Всегда ли можно сделать так, чтобы получилась ломаная линия без самопересечений, содержащая все отрезки?

Комментарии: 	 25	| ответить на задачу	  

*** Вписать треугольник	Геометрические задачи 		Вес: 5		Симпатии решивших: 88%		08.12.2010
Существует ли выпуклая плоская фигура, кроме круга, такая, что любой равносторонний треугольник со стороной 1 можно параллельным переносом вписать в нее? Треугольники отличаются ориентацией и положением центра на плоскости.

Комментарии: 	 30	| ответить на задачу	  

*** Герб	Геометрические задачи 		Вес: 5		Симпатии решивших: 83%		24.09.2010
На гербе одного древнего рода мегамозгов изображены четыре окружности одинакового радиуса: три красные и одна синяя. Причем любые две красных и синяя окружности пересекаются в одной точке. Докажите, что и все три красных окружности пересекаются в одной точке.

Комментарии: 	 9	| ответить на задачу	  

*** Раскраска бумаги	Геометрические задачи 		Вес: 5		Симпатии решивших: 83%		03.12.2011
Не отрывая карандаша от бумаги и не проходя по линии дважды, на плоскости нарисовали замкнутую кривую. Докажите, что образовавшиеся при этом области можно раскрасить в два цвета так, что никакие две смежные области не окажутся одноцветными.

Комментарии: 	 26	| ответить на задачу	  

*** Средний класс	Геометрические задачи 		Вес: 5		Симпатии решивших: 81%		06.03.2011
В Мозголяндии богатыми считаются люди, для которых существует расстояние R1, в радиусе которого они богаче большинства своих соседей. Бедными считаются люди, для которых существует расстояние R2, в радиусе которого они беднее большинства своих соседей. Средним классом в Мозголяндии называются люди, которых можно считать и богатыми, и бедными. Какой максимальный процент людей среднего класса может проживать в Мозголяндии?

Комментарии: 	 52	| ответить на задачу	  

*** Разрезание куба	Геометрические задачи 		Вес: 5		Симпатии решивших: 80%		10.02.2008
Можно ли куб разрезать на конечное количество кубиков меньшего размера так, чтобы все они были разными?

Комментарии: 	 22	| ответить на задачу	  

*** Коллекционер красивых камней	Геометрические задачи 		Вес: 5		Симпатии решивших: 78%		24.04.2008
Мегамозг коллекционировал разные камни и однажды нашел очень красивый экземпляр. Камень имел форму выпуклого многогранника и состоял из нескольких различных материалов. Всегда ли Мегамозг сможет положить такой камень на полку на одну из граней в устойчивом положении?

Комментарии: 	 39	| ответить на задачу	  

*** Четыре шара и цилиндр	Геометрические задачи 		Вес: 5		Симпатии решивших: 78%		19.02.2009
На бесконечной плоскости лежат 4 шара и 1 цилиндр, причем каждое из тел касается всех остальных. Цилиндр бесконечный в обе стороны. Радиус цилиндра равен 1. Требуется описать относительное расположение шаров и цилиндра, а также найти радиусы всех шаров.

Комментарии: 	 34	| ответить на задачу	  

*** Часовой на мосту	Геометрические задачи 		Вес: 5		Симпатии решивших: 62%		04.08.2008
Часовому было приказано ходить по одномерному мосту длиной 100 м в течение одного часа таким образом, чтобы побывать в каждой точке моста четное число раз (0, 2, 4 и т.д.). Стоять на месте и прыгать нельзя, т.к. мост заминирован и может взорваться. Начинать и заканчивать маршрут часовой может в любой точке моста по своему усмотрению. Сможет ли часовой придумать такой маршрут? Примечания: 1) скорость часового конечна, 2) разворачиваться часовой может мгновенно.

Комментарии: 	 68	| ответить на задачу	  

*** Задача на 100 баксов	Геометрические задачи 		Вес: 0		Симпатии решивших:		25.02.2011
Что это значит? Принимается первый наиболее точный ответ. За верное решение даю 100 баксов.

Комментарии: 	 72	| ответить на задачу	  

** Решенные
*** Цветная окружность	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		26.11.2006
Дана окружность, раскрашенная в 2 цвета — красный и синий. Доказать, что независимо от того, как именно она раскрашена, в нее всегда можно вписать равнобедренный треугольник так, что его вершины будут одного цвета.

**** Решение 
ОТВЕТ: (Дальше под раскраской подразумевается раскраска в два цвета). Допустим, что существует раскраска, для которой не существует равнобедренного треугольника с вершинами одного цвета. Для любой раскраски найдутся вершины одного цвета не диаметрально-противоположные. Действительно, среди любых трех вершин одного цвета найдутся две не диаметрально-противоположные. Если же количество вершин меньше трех, возьмем другой цвет. 

Через середину отрезка, соединяющего данные две вершины(под номером 1 и 2) одного цвета (цвет 1) проведем перпендикуляр. Очевидно, что его точки пересечения с окружностью(под номером 3 и 4) будут иметь другой цвет( цвет 2), иначе получим равнобедренный треугольник с вершинами одного цвета(1,2,3 или 1,2,4). Аналогично проведем перпендикуляр через отрезок, соединяющий две новые точки цвета 2. Точки пересечения с окружностью(номер 5, 6) будут диаметрально-противоположными и  иметь цвет 1(по той же причине). Получим еще две точки, симметрично отразив точки 1, 2 относительно отрезка (5,6)(номера новых точек - 7, 8). Точки 7 и 8 имеют цвет 2, иначе как минимум один из равнобедренных треугольников (6,1,8) или (5, 2, 7) будут одноцветными. Но тогда равнобедренные треугольники (4,7,8) и (3, 7, 8) будут одноцветными. То есть в любом случае найдется одноцветный треугольник.  

	ОБОСНОВАНИЕ:

	
*** Машинки на плоскости	Геометрические задачи 		Вес: 5		Симпатии решивших: 95%		14.02.2009
Четыре машинки едут на плоскости по прямым непараллельным линиям с постоянными скоростями. При столкновении каждая машинка продолжает движение, но может выдержать только две аварии — после третьей от нее ничего не остается. Пять столкновений уже произошло, причем в каждой аварии было только две машинки и двух машинок уже нет. Что будет с оставшимися двумя машинками, если известно, что их пути пересекутся в будущем?

