Denis178
* Геометрия
** Не решенные
*** Квадраты из спичек	Геометрические задачи 		Вес: 1		Симпатии решивших: 91%		29.11.2009
Из спичек выложена фигура, показанная на рисунке. Переложите 2 спички так, чтобы получилось 4 одинаковых квадрата. Каждая спичка должна быть частью квадрата.

Комментарии: 	 100	| ответить на задачу	  

*** Треугольники из спичек	Геометрические задачи 		Вес: 1		Симпатии решивших: 89%		29.11.2006
Есть 6 спичек. Сложите из них фигуру, состоящую только из четырех равносторонних треугольников. Ломать спички нельзя. Не должно остаться свободных концов спичек.

Комментарии: 	 83	| ответить на задачу	  

*** Прогулка по земному шару	Геометрические задачи 		Вес: 2		Симпатии решивших: 96%		27.11.2006
Мегамозг прошел одну милю на юг, одну милю на восток и одну милю на север и оказался в том месте, откуда отправлялся в путь. Где такое могло случиться?

Комментарии: 	 99	| ответить на задачу	  

*** Минное поле	Геометрические задачи 		Вес: 2		Симпатии решивших: 93%		03.05.2008
Близится наступление оккупантов. Известно, что оккупанты пройдут через поле сусликов. Главному мегамозгу приснилось, что для того, чтобы погибло максимальное число оккупантов, нужно расположить мины на десяти прямых по три штуки на каждой прямой. Но мин у мегамозгов всего 9. Как им расположить мины на поле?

Комментарии: 	 65	| ответить на задачу	  

*** Треугольнутая фигура	Геометрические задачи 		Вес: 2		Симпатии решивших: 78%		03.08.2010
Нарисуйте фигуру, которую можно разрезать как на 3, так и на 4 равных треугольника.

Комментарии: 	 26	| ответить на задачу	  

*** Построить квадрат	Геометрические задачи 		Вес: 3		Симпатии решивших: 95%		11.12.2009
Как построить квадрат с помощью очень длинной односторонней линейки с 2 метками? (Примечания: Такая линейка позволяет проводить только прямые и откладывать заданный отрезок. Сторона построенного квадрата может быть произвольной.)

Комментарии: 	 48	| ответить на задачу	  

*** Развертка куба	Геометрические задачи 		Вес: 3		Симпатии решивших: 94%		13.12.2008
Как из квадрата бумаги 3х3 вырезать фигуру, представляющую собой развертку полной поверхности единичного куба?

Комментарии: 	 48	| ответить на задачу	  

Пилим куб	Геометрические задачи 		Вес: 3		Симпатии решивших: 91%		08.12.2006
За какое минимальное количество распилов можно распилить куб 3×3×3 на составные кубики 1×1×1? Каждый распил может проходить через несколько уже отпиленных кусков. Минимальность обосновать.

Комментарии: 	 25	| ответить на задачу	  

*** Тетрис	Геометрические задачи 		Вес: 3		Симпатии решивших: 90%		26.02.2012
Минимозгу нужно решить три уравнения: соединить детали так, чтобы по обе стороны знака равенства были одинаковые фигуры. Детали можно вращать и отображать зеркально. Помогите ему справиться с заданием.

Комментарии: 	 47	| ответить на задачу	  

*** Треугольники из спичек — 2	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		19.02.2009
Как из 6 спичек сложить 1 равносторонний и 3 равнобедренных (не равносторонних) треугольника? Не ломать. Нельзя накладывать одну спичку на другую. Не должно остаться свободных концов спичек.

Комментарии: 	 69	| ответить на задачу	  

*** Третья проекция	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		29.12.2010
Даны две проекции предмета (см. рисунок). Нарисуйте третью проекцию, при условии что предмет объемный, цельный и все его грани плоские. Приведите не менее четырех вариантов решения.

Комментарии: 	 49	| ответить на задачу	  

*** Разрезание параллелограмма	Геометрические задачи 		Вес: 4		Симпатии решивших: 95%		25.04.2007
Как разрезать параллелограмм на 9 равнобедренных треугольников?

Комментарии: 	 68	| ответить на задачу	  

*** Флаг	Геометрические задачи 		Вес: 4		Симпатии решивших: 94%		14.03.2008
На двуцветном прямоугольном флаге страны Мозголяндии всегда было 14 одинаковых по ширине полосок чередующихся цветов — по полосе на каждого из местных мегамозгов. Вчера правительство соседней Мозголии приняло решение о натурализации двух мегамозгов из Мозголяндии, и они получили новое гражданство. Оказалось, что материал, из которого делали флаг Мозголяндии, больше не производят, сам флаг старый и хлипкий и поэтому его нельзя разрезать больше чем на две части, а традицию надо соблюсти. Что делать мозголяндцам, среди которых стало на два мегамозга меньше, если теперь им нужен прямоугольный флаг с 12-ю полосками максимальной площади?

Комментарии: 	 56	| ответить на задачу	  

*** Четыре коня	Геометрические задачи 		Вес: 4		Симпатии решивших: 89%		27.11.2008
Есть обычная шахматная доска, на которой стоят по главной диагонали 4 коня (поля h1, g2, f3, е4). Требуется разделить доску на 4 равные, одинаковые по форме части таким образом, чтобы в каждой было по одному коню. Каждая часть должна быть связной (состоять из одного куска).

Комментарии: 	 46	| ответить на задачу	  

*** Разрезать круг	Геометрические задачи 		Вес: 4		Симпатии решивших: 89%		14.12.2009
Разрежьте круг на несколько равных (совпадающих при наложении) частей так, чтобы центр круга не лежал на границе хотя бы одной из них.

Комментарии: 	 45	| ответить на задачу	  

*** Дремучий лес	Геометрические задачи 		Вес: 4		Симпатии решивших: 87%		22.08.2009
Мегамозг находится в дремучем лесу, который по площади занимает ровно 100 км2. Форма леса неизвестна, но лес сплошной, без полян. Мегамозг хочет выбраться из леса, пройдя минимально возможное расстояние. Путь какой минимальной длины (и формы) гарантирует, что удастся найти границу леса?

Комментарии: 	 41	| ответить на задачу	  

Разрезать квадрат	Геометрические задачи 		Вес: 4		Симпатии решивших: 82%		19.10.2009
Разрезать квадрат на минимальное число остроугольных треугольников. Доказательство минимальности не требуется.

Комментарии: 	 31	| ответить на задачу	  

*** Телефонный кабель	Геометрические задачи 		Вес: 5		Симпатии решивших: 96%		14.05.2008
Мегамозг работал телефонистом, и однажды ему позвонил диспетчер из офиса и попросил найти закопанный кабель. Кабель был проложен на небольшой глубине по прямой, проходящей ровно в 5 км от той точки, где находился Мегамозг. К сожалению, связь прервалась и диспетчер не успел уточнить, в каком направлении проходит кабель. У Мегамозга есть металлоискатель, который звенит точно над кабелем. Может ли он спланировать свой путь так, чтобы гарантированно найти кабель, пройдя при этом не более 32 км?

Комментарии: 	 74	| ответить на задачу	  

*** Храм	Геометрические задачи 		Вес: 5		Симпатии решивших: 94%		04.10.2011
Вызвал к себе король придворного архитектора, и дал ему задание: "Построй мне храм, и чтобы была в нем лишь одна комната. Стены в ней пусть будут зеркальными, а углов не будет вовсе. Хочу, чтобы она освещалась единственной свечкой, но и неосвещенное место должно остаться." Как архитектору справиться с поставленной задачей?

Комментарии: 	 64	| ответить на задачу	  

*** Луч в кубе	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		13.02.2008
Луч света, направленный из вершины куба, отразившись 2008 раз от его внутренних зеркальных стенок (по закону «угол падения равен углу отражения») и не попадая при этом на ребра, заканчивает свой путь в другой вершине куба. Какое наименьшее расстояние может пройти луч света, если длина ребра куба равна 1?

Комментарии: 	 37	| ответить на задачу	  

*** Мегамозг и яблоко	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		16.08.2008
Однажды Мегамозг шел по улице и увидел плачущего мальчика с яблоком. «Что ты плачешь, мальчик?» — спросил Мегамозг. — «Да вот, яблоко червивое попалось». — «Ничего страшного, — сказал Мегамозг. — Радиус яблока 40 мм, а червяк прогрыз сквозной путь длиной не более 79 мм, и поэтому я сейчас разрежу твое яблоко на два полушария так, что одно из полушарий не будет червивым». Верно ли, что Мегамозг всегда сможет это сделать?
Примечание: яблоко разрезается плоскостью, проходящей через центр; размерами червяка пренебречь.

Комментарии: 	 50	| ответить на задачу	  

*** Рациональный тетраэдр	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		07.10.2009
Можно ли в декартовой системе координат расположить правильный тетраэдр так, чтобы все его вершины лежали в точках с целочисленными координатами?

Комментарии: 	 26	| ответить на задачу	  

*** Внутренняя граница	Геометрические задачи 		Вес: 5		Симпатии решивших: 93%		19.12.2011
Мозголяндия имеет форму правильного треугольника. Внутренняя граница делит ее на два равных по площади штата. Опишите форму и расположение границы, если известно, что она непрерывна и имеет минимально возможную длину.

Комментарии: 	 17	| ответить на задачу	  

*** Лачуга в междуречье	Геометрические задачи 		Вес: 5		Симпатии решивших: 92%		06.07.2009
Приток при впадении в реку образует острый угол. На суше, внутри угла, стоит лачуга Мегамозга. Каждый день Мегамозг выходит из нее, идет к притоку, встречает рассвет, затем отправляется к реке, встречает закат и возвращается в лачугу. Как нужно Мегамозгу проложить маршрут, чтобы путь, проходимый им каждый день, был минимален? Считать берега реки и притока прямыми линиями.

Комментарии: 	 44	| ответить на задачу	  

*** Телефонный кабель — 2	Геометрические задачи 		Вес: 5		Симпатии решивших: 92%		26.08.2009
У Мегамозга есть квадратный участок земли со стороной 1 км. Он случайно узнал, что подлые оккупанты тайно проложили телефонный кабель под его участком и используют его для своих грязных оккупантских целей. Кабель прямой и лежит на небольшой глубине (за пределами участка Мегамозга кабель идёт на той же самой глубине и по той же самой прямой на много километров в обе стороны). Узнав об этой подлости, Мегамозг схватил лопату и... задумался. Какой минимальной длины (и какой формы) нужно прокопать траншею, чтобы наверняка найти кабель? Траншея не обязательно должна состоять из связных кусков, она может быть разрывная. Доказательство минимальности не требуется.

Комментарии: 	 35	| ответить на задачу	  

*** Треугольный торт	Геометрические задачи 		Вес: 5		Симпатии решивших: 91%		26.02.2009
Торт имеет форму произвольного треугольника. Два мегамозга делят его следующим образом: первый указывает на торте точку, второй проводит через эту точку прямолинейный разрез и забирает себе большую часть. Какую наибольшую часть торта может обеспечить себе первый мегамозг? Считается, что торт всюду имеет одинаковую толщину.

Комментарии: 	 25	| ответить на задачу

**** Решение

*** Нарисуй ломаную	Геометрические задачи 		Вес: 5		Симпатии решивших: 89%		27.12.2011
На плоскости нарисовано конечное число непересекающихся отрезков. Разрешается соединять свободные концы любых двух отрезков третьим отрезком. Всегда ли можно сделать так, чтобы получилась ломаная линия без самопересечений, содержащая все отрезки?

Комментарии: 	 25	| ответить на задачу	  

*** Вписать треугольник	Геометрические задачи 		Вес: 5		Симпатии решивших: 88%		08.12.2010
Существует ли выпуклая плоская фигура, кроме круга, такая, что любой равносторонний треугольник со стороной 1 можно параллельным переносом вписать в нее? Треугольники отличаются ориентацией и положением центра на плоскости.

Комментарии: 	 30	| ответить на задачу	  

*** Герб	Геометрические задачи 		Вес: 5		Симпатии решивших: 83%		24.09.2010
На гербе одного древнего рода мегамозгов изображены четыре окружности одинакового радиуса: три красные и одна синяя. Причем любые две красных и синяя окружности пересекаются в одной точке. Докажите, что и все три красных окружности пересекаются в одной точке.

Комментарии: 	 9	| ответить на задачу	  

*** Раскраска бумаги	Геометрические задачи 		Вес: 5		Симпатии решивших: 83%		03.12.2011
Не отрывая карандаша от бумаги и не проходя по линии дважды, на плоскости нарисовали замкнутую кривую. Докажите, что образовавшиеся при этом области можно раскрасить в два цвета так, что никакие две смежные области не окажутся одноцветными.

Комментарии: 	 26	| ответить на задачу	  

*** Средний класс	Геометрические задачи 		Вес: 5		Симпатии решивших: 81%		06.03.2011
В Мозголяндии богатыми считаются люди, для которых существует расстояние R1, в радиусе которого они богаче большинства своих соседей. Бедными считаются люди, для которых существует расстояние R2, в радиусе которого они беднее большинства своих соседей. Средним классом в Мозголяндии называются люди, которых можно считать и богатыми, и бедными. Какой максимальный процент людей среднего класса может проживать в Мозголяндии?

Комментарии: 	 52	| ответить на задачу	  

*** Разрезание куба	Геометрические задачи 		Вес: 5		Симпатии решивших: 80%		10.02.2008
Можно ли куб разрезать на конечное количество кубиков меньшего размера так, чтобы все они были разными?

Комментарии: 	 22	| ответить на задачу	  

*** Коллекционер красивых камней	Геометрические задачи 		Вес: 5		Симпатии решивших: 78%		24.04.2008
Мегамозг коллекционировал разные камни и однажды нашел очень красивый экземпляр. Камень имел форму выпуклого многогранника и состоял из нескольких различных материалов. Всегда ли Мегамозг сможет положить такой камень на полку на одну из граней в устойчивом положении?

Комментарии: 	 39	| ответить на задачу	  

*** Четыре шара и цилиндр	Геометрические задачи 		Вес: 5		Симпатии решивших: 78%		19.02.2009
На бесконечной плоскости лежат 4 шара и 1 цилиндр, причем каждое из тел касается всех остальных. Цилиндр бесконечный в обе стороны. Радиус цилиндра равен 1. Требуется описать относительное расположение шаров и цилиндра, а также найти радиусы всех шаров.

Комментарии: 	 34	| ответить на задачу	  

*** Часовой на мосту	Геометрические задачи 		Вес: 5		Симпатии решивших: 62%		04.08.2008
Часовому было приказано ходить по одномерному мосту длиной 100 м в течение одного часа таким образом, чтобы побывать в каждой точке моста четное число раз (0, 2, 4 и т.д.). Стоять на месте и прыгать нельзя, т.к. мост заминирован и может взорваться. Начинать и заканчивать маршрут часовой может в любой точке моста по своему усмотрению. Сможет ли часовой придумать такой маршрут? Примечания: 1) скорость часового конечна, 2) разворачиваться часовой может мгновенно.

Комментарии: 	 68	| ответить на задачу	  

*** Задача на 100 баксов	Геометрические задачи 		Вес: 0		Симпатии решивших:		25.02.2011
Что это значит? Принимается первый наиболее точный ответ. За верное решение даю 100 баксов.

Комментарии: 	 72	| ответить на задачу	  

** Решенные
*** Цветная окружность	Геометрические задачи 		Вес: 4		Симпатии решивших: 96%		26.11.2006
Дана окружность, раскрашенная в 2 цвета — красный и синий. Доказать, что независимо от того, как именно она раскрашена, в нее всегда можно вписать равнобедренный треугольник так, что его вершины будут одного цвета.

**** Решение 
ОТВЕТ: (Дальше под раскраской подразумевается раскраска в два цвета). Допустим, что существует раскраска, для которой не существует равнобедренного треугольника с вершинами одного цвета. Для любой раскраски найдутся вершины одного цвета не диаметрально-противоположные. Действительно, среди любых трех вершин одного цвета найдутся две не диаметрально-противоположные. Если же количество вершин меньше трех, возьмем другой цвет. 

Через середину отрезка, соединяющего данные две вершины(под номером 1 и 2) одного цвета (цвет 1) проведем перпендикуляр. Очевидно, что его точки пересечения с окружностью(под номером 3 и 4) будут иметь другой цвет( цвет 2), иначе получим равнобедренный треугольник с вершинами одного цвета(1,2,3 или 1,2,4). Аналогично проведем перпендикуляр через отрезок, соединяющий две новые точки цвета 2. Точки пересечения с окружностью(номер 5, 6) будут диаметрально-противоположными и  иметь цвет 1(по той же причине). Получим еще две точки, симметрично отразив точки 1, 2 относительно отрезка (5,6)(номера новых точек - 7, 8). Точки 7 и 8 имеют цвет 2, иначе как минимум один из равнобедренных треугольников (6,1,8) или (5, 2, 7) будут одноцветными. Но тогда равнобедренные треугольники (4,7,8) и (3, 7, 8) будут одноцветными. То есть в любом случае найдется одноцветный треугольник.  

	ОБОСНОВАНИЕ:

	
*** Машинки на плоскости	Геометрические задачи 		Вес: 5		Симпатии решивших: 95%		14.02.2009
Четыре машинки едут на плоскости по прямым непараллельным линиям с постоянными скоростями. При столкновении каждая машинка продолжает движение, но может выдержать только две аварии — после третьей от нее ничего не остается. Пять столкновений уже произошло, причем в каждой аварии было только две машинки и двух машинок уже нет. Что будет с оставшимися двумя машинками, если известно, что их пути пересекутся в будущем?


* Все 5 баллов
Повесить картину 	Логические задачи  		Вес: 5 		Симпатии решивших: 100% 		10.12.2010
К картине обоими концами прикреплена длинная веревка. Необходимо повесить картину на стену с помощью N гвоздей так, чтобы при вытаскивании любого гвоздя картина и веревка падали. Как это сделать?

Колпаки с числами 	Логические задачи  		Вес: 5 		Симпатии решивших: 97% 		21.05.2007
Ста мегамозгам на головы надели колпаки с числами из диапазона 1..100, причем не обязательно, что на всех разные. К примеру, всем могли надеть колпак с числом 7 или половине — колпак с числом 20, а второй половине — с числом 10. Главное, что не меньше 1 и не больше 100. После этого всех их поставили по кругу. Каждый мегамозг видит 99 чисел на головах других, но не свое. После этого каждый пишет на листке бумаги число от 1 до 100 — предполагаемое число на своём колпаке. Общаться и подглядывать нельзя ;) Их всех отпустят, если хотя бы один угадает свое число. Какой стратегии они должны придерживаться, если хотят, чтобы их гарантированно отпустили? (Мегамозги могли заранее договориться о стратегии).

Коробки с именами 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 97% 		08.08.2007
Подлые оккупанты захватили четырех мегамозгов и сказали, что их соберут вместе, дадут 5 минут на совещание, а дальше будут по одному заводить в комнату, где находятся 4 коробки в линию. В каждой коробке находится имя ровно одного мегамозга, имена всех мегамозгов присутствуют, все имена различны. Их всех по очереди заводят в комнату с коробками. Мегамозг при заходе в комнату должен будет открыть 2 коробки в поисках своего имени. После этого мегамозга выводят через другую дверь и он больше не встречается с остальными до конца испытания. Коробки приводятся в исходное состояние, и заходит следующий мегамозг. Их отпустят только в том случае, если каждый найдет свое имя, иначе все будут казнены. О чем договорились мегамозги и какие у них шансы выжить? (Доказательство оптимальности стратегии не требуется).

Сортировка мегамозгов 	Логические задачи  		Вес: 5 		Симпатии решивших: 97% 		19.12.2010
Деревня мегамозгов в очередной раз была захвачена оккупантами. В этот раз оккупанты придумали следующее: на лбу каждого мегамозга пишут произвольное натуральное число (все числа разные) и дают каждому по красному и синему колпаку. После чего по сигналу все мегамозги должны одновременно выбрать один из колпаков и надеть его себе на голову. Затем мегамозгов строят в шеренгу в порядке возрастания чисел, написанных на их лбах. Если при этом цвета колпаков в шеренге чередуются — всех отпускают, иначе — всех убивают. Мегамозгам сообщили правила и дали возможность заранее договориться. Смогут ли они гарантированно выжить?

Таинственная фигура 	Шахматы и шашки  		Вес: 5 		Симпатии решивших: 97% 		21.06.2011
Ход черных. Какая фигура стоит на g4? Рисунок

Альтернативные кости 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 97% 		13.06.2012
Несложно посчитать вероятность выпадения определенной суммы на паре обычных игральных кубиков: сумма «2» будет выпадать с вероятностью 1/36, «3» - 2/36 и т.д. Существует ли иная раскладка натуральных чисел на паре кубиков, дающая те же вероятности для тех же самых сумм?

Телефонный кабель 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 96% 		14.05.2008
Мегамозг работал телефонистом, и однажды ему позвонил диспетчер из офиса и попросил найти закопанный кабель. Кабель был проложен на небольшой глубине по прямой, проходящей ровно в 5 км от той точки, где находился Мегамозг. К сожалению, связь прервалась и диспетчер не успел уточнить, в каком направлении проходит кабель. У Мегамозга есть металлоискатель, который звенит точно над кабелем. Может ли он спланировать свой путь так, чтобы гарантированно найти кабель, пройдя при этом не более 32 км?

Правдивые этикетки 	Взвешивания  		Вес: 5 		Симпатии решивших: 96% 		23.02.2009
Имеется 6 гирек весом 1, 2, 3, 4, 5, 6 граммов. На них наклеены этикетки 1, 2, 3, 4, 5, 6. За какое наименьшее количество взвешиваний на чашечных весах без стрелки можно выяснить, правильно ли наклеены этикетки?

Расставить скобки и знаки 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 96% 		30.12.2009
В строку выписано 32 натуральных числа (не обязательно различных). Докажите, что между ними можно так расставить скобки, знаки сложения и умножения, чтобы значение полученного выражения делилось нацело на 11000.

Флажки 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 95% 		26.12.2008
Оккупанты в очередной раз устраивают Мегамозгу испытание. На большом поле они воткнули в землю 30 флажков и нарисовали окружность радиусом 100 метров. Все, что может сделать Мегамозг, — выбрать точку на окружности, из которой будет стартовать оккупантский бегун. Бегун бежит со скоростью 10 метров в секунду. Он должен выбежать из начальной точки, добежать до флажка, принести его в начальную точку, добежать до следующего флажка, принести его в начальную точку и т.д. (выдергивает флажки, бросает их и разворачивается бегун мгновенно). Если он успеет принести все флажки в начальную точку за 10 минут — Мегамозга расстреляют. Всегда ли Мегамозг может спастись, правильно выбрав начальную точку? Флажки воткнуты в разных точках.

Цезарь и Брут 	Игры  		Вес: 5 		Симпатии решивших: 95% 		24.04.2009
Два полководца (Цезарь и Брут) захватывают некую страну, представляющую собой города, некоторые из которых соединены дорогами так, что из любого города можно дойти по дорогам в любой другой. В первый ход сначала Цезарь выбирает любой город и захватывает его, потом Брут выбирает любой незахваченный город и захватывает его. Далее каждый по очереди (начиная с Цезаря) выбирает любой незахваченный никем город, соединенный с уже захваченным им городом, и захватывает его. Игра продолжается, пока не будут захвачены все города. Каждый хочет захватить как можно больше городов. Если в какой-то момент один из игроков не может захватить город, он пропускает ход. Может ли случиться, что Брут захватит городов больше, чем Цезарь?

Погоня 	Логические задачи  		Вес: 5 		Симпатии решивших: 95% 		13.02.2011
Мегамозг преследует подлого Оккупанта-преступника, который пытается скрыться в подвале своего дома. Подвал представляет собой 3 узких прямых коридора одинаковой длины, расходящихся в виде пропеллера из маленькой комнаты и заканчивающихся тупиком. В подвале темно, и Мегамозг может разглядеть преступника только с расстояния, не превышающего 10 м. Скорость Мегамозга в два раза больше скорости Оккупанта. При какой максимальной длине коридоров Мегамозг может гарантированно поймать преступника (доказательство оптимальности не требуется)?

Храм 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 95% 		04.10.2011
Вызвал к себе король придворного архитектора, и дал ему задание: «Построй мне храм, и чтобы была в нем лишь одна комната. Стены в ней пусть будут зеркальными, а углов не будет вовсе. Хочу, чтобы она освещалась единственной свечкой, но и неосвещенное место должно остаться». Как архитектору справиться с поставленной задачей?

Расскажи другу 	Логические задачи  		Вес: 5 		Симпатии решивших: 95% 		11.07.2012
Семь разных костей домино показали двум мегамозгам и оккупанту, перемешали и раздали мегамозгам по три. Возможности заранее договориться у мегамозгов не было. Получится ли у них, открыто общаясь, сообщить друг другу свои кости так, чтобы оккупант не смог вычислить местонахождение ни одной из костей, которых он не видит, если оставшуюся кость: а) спрятали; б) отдали оккупанту?

Пирожки 	Игры  		Вес: 5 		Симпатии решивших: 94% 		07.12.2006
Два мегамозга играют в игру. Каждый по очереди берет из кучи пирожков 1, 2 или 3 пирожка и съедает их. При этом он не может взять столько, сколько взял соперник предыдущим ходом. Выигрывает тот, кто съедает последний пирожок или после чьего хода соперник свой ход сделать не может. Кто из них выиграет при правильной игре, если сначала в куче было 2000 пирожков?

Испорченная шахматная доска 	Логические задачи  		Вес: 5 		Симпатии решивших: 94% 		02.10.2007
Из шахматной доски вырезали одну угловую клетку. Можно ли покрыть оставшуюся часть доски (63 клетки) с помощью 21 прямоугольного куска картона размером 1x3 клетки?

Игра с суммами 	Игры  		Вес: 5 		Симпатии решивших: 94% 		08.07.2008
Двое играют в следующую игру. На столе в ряд выложено четное число карточек с числами. Игроки по очереди берут одну из карточек с любого из концов ряда. Выигравший должен набрать бОльшую сумму, иначе ничья. Кто не проигрывает в этой игре? Какова непроигрышная стратегия?

Трапеция 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 94% 		15.07.2008
Дана трапеция (произвольная). Как с помощью одной линейки (без делений) разделить нижнее основание трапеции на 3 равные части?

Рациональный тетраэдр 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 94% 		07.10.2009
Можно ли в декартовой системе координат расположить правильный тетраэдр так, чтобы все его вершины лежали в точках с целочисленными координатами?

Игра в 15 	Игры  		Вес: 5 		Симпатии решивших: 94% 		08.10.2009
Два игрока играют в следующую игру. На бумаге выписаны числа от 1 до 9, игроки по очереди закрывают любую из цифр фишкой своего цвета. Выигрывает тот участник, который первым закроет своими фишками три числа, сумма которых равна 15 (если игрок закрыл больше трех чисел, то он выигрывает, если сумма хотя бы одной из троек чисел равна 15). Есть ли в этой игре выигрышная стратегия? Если есть, то у какого игрока и какая?

Именные футболки 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 94% 		09.09.2010
Ко Дню мегамозга было выпущено N именных футболок, строго по одной на каждого. Предполагалось, что мегамозги по одному в определенном порядке будут заходить в комнату, находить свою футболку, надевать её и выходить. Но к сожалению, первый мегамозг выбыл из строя и на его место был поставлен минимозг, которому именную футболку не успели сделать. Процедура осталась той же, но минимозг, зайдя в комнату первым, надевает любую попавшуюся ему футболку. Далее каждый мегамозг, если не находит свою футболку, надевает любую другую из оставшихся. Какова вероятность того, что последний зашедший в комнату наденет свою футболку?

По семь карт 	Преферанс  		Вес: 5 		Симпатии решивших: 94% 		05.01.2011
В «Школе преферанса» троим ученикам раздали по 7 карт (см. рисунок). Все карты открыты. Играет Юг. Козырь черви. Ход Запада. Сколько взяток сможет взять Юг при правильной игре соперников?

Пузырек 	Физические задачи  		Вес: 5 		Симпатии решивших: 94% 		29.07.2011
На дне цилиндрической цистерны, полностью заполненной водой, находится небольшой пузырек воздуха. В некоторый момент времени пузырек отрывается от дна и всплывает к крышке цистерны. На сколько при этом изменится давление на дно цистерны, если её высота составляет 1 метр? Цистерна герметична.

Клетчатая эпидемия 	Логические задачи  		Вес: 5 		Симпатии решивших: 93% 		04.03.2008
Некоторые клетки шахматной доски (8×8) заражены вирусом. Если у клетки имеются два или больше зараженных соседа (по стороне), то она становится зараженной. Например, если вначале заражена вся главная диагональ, то на первом шаге заражаются 14 соседних с ней клеток, на втором — еще 12 и т.д., пока вся доска не окажется зараженной. Докажите, что если вначале на доске менее 8 зараженных клеток, то на доске всегда останутся незараженные клетки.

Мегамозг и яблоко 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 93% 		16.08.2008
Однажды Мегамозг шел по улице и увидел плачущего мальчика с яблоком. «Что ты плачешь, мальчик?» — спросил Мегамозг. — «Да вот, яблоко червивое попалось». — «Ничего страшного, — сказал Мегамозг. — Радиус яблока 40 мм, а червяк прогрыз сквозной путь длиной не более 79 мм, и поэтому я сейчас разрежу твое яблоко на два полушария так, что одно из полушарий не будет червивым». Верно ли, что Мегамозг всегда сможет это сделать?

Примечание: яблоко разрезается плоскостью, проходящей через центр; размерами червяка пренебречь.

Лачуга в междуречье 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 93% 		06.07.2009
Приток при впадении в реку образует острый угол. На суше, внутри угла, стоит лачуга Мегамозга. Каждый день Мегамозг выходит из нее, идет к притоку, встречает рассвет, затем отправляется к реке, встречает закат и возвращается в лачугу. Как нужно Мегамозгу проложить маршрут, чтобы путь, проходимый им каждый день, был минимален? Считать берега реки и притока прямыми линиями.

Таинственная фигура — 2 	Шахматы и шашки  		Вес: 5 		Симпатии решивших: 93% 		13.12.2011
Какая фигура в этой позиции стоит на поле h4?

Хоккеист 	Физические задачи  		Вес: 5 		Симпатии решивших: 92% 		20.04.2007
Хоккеист бьет по шайбе, после чего та движется по шероховатому льду. Возможно подкрутить или не подкрутить шайбу (поступательную скорость в обоих случаях считать одинаковой). В каком случае шайба дальше проедет? Сопротивлением воздуха пренебречь. Лед не плавится.

Луч в кубе 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 92% 		13.02.2008
Луч света, направленный из вершины куба, отразившись 2008 раз от его внутренних зеркальных стенок (по закону «угол падения равен углу отражения») и не попадая при этом на ребра, заканчивает свой путь в другой вершине куба. Какое наименьшее расстояние может пройти луч света, если длина ребра куба равна 1?

Треугольный торт 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 92% 		26.02.2009
Торт имеет форму произвольного треугольника. Два мегамозга делят его следующим образом: первый указывает на торте точку, второй проводит через эту точку прямолинейный разрез и забирает себе большую часть. Какую наибольшую часть торта может обеспечить себе первый мегамозг? Считается, что торт всюду имеет одинаковую толщину.

Три фишки в ряд 	Игры  		Вес: 5 		Симпатии решивших: 92% 		14.09.2009
Есть полоска, разделенная на N клеток, расположенных горизонтально в ряд (N > 3). На первых трех клетках, если считать справа, стоит по фишке. Двое играют в игру, в которой каждым ходом любая фишка перемещается влево на любую свободную клетку (разрешается перепрыгивать через другие фишки). Игроки ходят по очереди. Проигрывает тот, кто не может сделать очередной ход. У кого есть выигрышная стратегия?

Обмен шифрами 	Логические задачи  		Вес: 5 		Симпатии решивших: 92% 		01.02.2011
Каждому из двух мегамозгов необходимо передать другому шифр незаметно для оккупантов. Они подходят к речке, на берегу которой лежит кучка из 26 одинаковых камней, и строго по очереди начинают кидать камни в воду. За раз бросают как минимум один, расходятся, когда камней больше не осталось. Смогут ли мегамозги обменяться информацией, если шифр - любое число от 1 до 1700?

Король-невидимка 	Шахматы и шашки  		Вес: 5 		Симпатии решивших: 92% 		30.05.2011
На одной из клеток шахматной доски стоит невидимый белый король. Ход чёрных. Могут ли они поставить мат за один ход?

Вес футболистов 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 91% 		21.07.2008
Однажды 23 мегамозга решили сыграть в футбол. В процессе выбора команд они заметили интересную особенность: кого бы ни выбирали судьей матча, остальные 22 игрока могли разделиться на две команды по 11 человек с равным суммарным весом всех игроков. Известно, что вес каждого мегамозга выражался целым числом килограммов. Возможно ли такое, что не все мегамозги имели одинаковый вес?

Телефонный кабель — 2 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 91% 		26.08.2009
У Мегамозга есть квадратный участок земли со стороной 1 км. Он случайно узнал, что подлые оккупанты тайно проложили телефонный кабель под его участком и используют его для своих грязных оккупантских целей. Кабель прямой и лежит на небольшой глубине (за пределами участка Мегамозга кабель идёт на той же самой глубине и по той же самой прямой на много километров в обе стороны). Узнав об этой подлости, Мегамозг схватил лопату и... задумался. Какой минимальной длины (и какой формы) нужно прокопать траншею, чтобы наверняка найти кабель? Траншея не обязательно должна состоять из связных кусков, она может быть разрывная. Доказательство минимальности не требуется.

Бракованные резисторы 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 91% 		14.09.2010
Мегамозг собрал цепь, как показано на картинке. Однако все резисторы, которые он использовал, сделаны подлыми оккупантами, и поэтому каждый из них с вероятностью 50% бракованный. Бракованный резистор выглядит как обычный, но ток не проводит. С какой вероятностью после замыкания ключа по цепи Мегамозга все-таки пойдет ток?

Столб кирпичей 	Физические задачи  		Вес: 5 		Симпатии решивших: 91% 		14.10.2010
Представим, что у нас столб лежащих друг на друге кирпичей. Разрешается сдвигать друг относительно друга по плоскости кирпич, лежащий на другом кирпиче. На какое максимальное расстояние можно сдвинуть верхний кирпич относительно самого нижнего? Столб сколь угодно высокий.

Внутренняя граница 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 91% 		19.12.2011
Мозголяндия имеет форму правильного треугольника. Внутренняя граница делит ее на два равных по площади штата. Опишите форму и расположение границы, если известно, что она непрерывна и имеет минимально возможную длину.

Игра с разменными монетами 	Игры  		Вес: 5 		Симпатии решивших: 90% 		20.10.2006
Два игрока по очереди называют натуральное число — достоинство воображаемой разменной монеты. При этом нужно, чтобы это число нельзя было выплатить при помощи ранее названных монет. Проигрывает назвавший число 1. Доказать, что игра не может продолжаться бесконечно.

Кролики 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 90% 		05.12.2006
Мегамозг вошел в зоомагазин и купил двух плюс половину из оставшихся кроликов. Второй мегамозг купил трех плюс треть оставшихся кроликов. Третий мегамозг купил четырех плюс четверть оставшихся кроликов. И так далее, пока не стало больше возможным разделять кроликов. Сколько максимум мегамозгов могло купить кроликов?

Игра со стержнями 	Игры  		Вес: 5 		Симпатии решивших: 90% 		22.04.2009
Два мегамозга играют в игру. Имеется 100 деревянных стержней с длинами 1, 2, ..., 100 мегадюймов. Каждый по очереди выбирает 3 стержня, складывает из них треугольник и сжигает его. Проигрывает тот, кто не может сделать ход. У кого из игроков есть выигрышная стратегия?

Три палочки 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 90% 		22.01.2010
У мегамозга есть три палочки. Если из них нельзя сложить треугольник, он укорачивает самую длинную из палочек на сумму длин двух других. Если длина палочки не обратилась в нуль и треугольник снова нельзя сложить, то мегамозг повторяет операцию, и т. д. Может ли этот процесс продолжаться бесконечно?

Автобусы на маршруте 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 90% 		28.12.2010
Мегамозг-провинциал ежедневно ездит на работу в областной город. Единственный автобус подходящего маршрута выезжает на линию каждый день в разное (случайное) время и проходит весь путь туда и обратно за 2 часа. Поэтому Мегамозгу приходится ждать на остановке от 0 до 2 часов (в среднем — 1 час). Но со следующей недели транспортная компания решила выпустить на линию еще 9 автобусов. Как и раньше, каждый из них будет выезжать в случайный момент времени и проходить весь путь за 2 часа. Сколько в среднем Мегамозгу придется ждать автобус после этого нововведения?

Краб в аквариуме 	Физические задачи  		Вес: 5 		Симпатии решивших: 90% 		31.01.2011
На идеально гладком полу стоит стеклянный аквариум с 20 литрами воды. На дне аквариума, под водой, спит краб, плотностью 2 г/см³ и объемом 100 см³. Краб просыпается и ползет к стенке со скоростью 1 см/с относительно аквариума. С какой скоростью будет двигаться аквариум относительно пола, если масса пустого аквариума 5 кг?

Нарисуй ломаную 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 90% 		27.12.2011
На плоскости нарисовано конечное число непересекающихся отрезков. Разрешается соединять свободные концы любых двух отрезков третьим отрезком. Всегда ли можно сделать так, чтобы получилась ломаная линия без самопересечений, содержащая все отрезки?

Лестницы без ступенек 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 89% 		29.05.2007
Мегамозг хочет забраться на крышу своего дома по приставной лестнице. В кладовке лежит много лестниц, но, к сожалению, у большинства из них не хватает ступенек. По лестницам, у которых отсутствуют две ступеньки подряд, Мегамозг забраться не может. Все его лестницы изначально были с N ступеньками. У всех лестниц четко определен низ и верх. Сколько существует вариантов лестниц, по которым Мегамозг мог бы забраться?

Мегамозг и выборы 	Логические задачи  		Вес: 5 		Симпатии решивших: 89% 		10.04.2008
В одной латиноамериканской стране, где правит Мегамозг, пришло время новых выборов руководителя страны. В стране ровно 100 000 000 человек, обладающих правом голоса. Из них только 1% поддерживает Мегамозга. Но Мегамозг, чтобы казаться «демократичным» в глазах мировой общественности, хочет быть «честно избран». Процедура голосования в этой стране следующая: Мегамозг разделяет всех избирателей на некоторое количество равных групп, затем эти группы – еще на несколько равных групп и т.д. В полученных самых маленьких группах – люди избирают делегата, затем выбранные выборщики выбирают в большей группе следующего делегата и так далее. В конце представители самых больших групп избирателей выбирают руководителя страны. Мегамозг сам разделяет население на группы. Может ли он провести выборы так, чтобы его «демократично» избрали? (При равенстве голосов побеждает оппозиционный кандидат от Оккупантов).

Автомобиль — 2 	Логические задачи  		Вес: 5 		Симпатии решивших: 89% 		08.05.2008
Есть кольцевая дорога длиной 100 км, на которой произвольным образом разбросано конечное число бочек с горючим. Суммарное количество горючего в бочках — 100 л, но распределение горючего по бочкам произвольно. Есть автомобиль с расходом топлива 1 л/км и пустым баком вместимостью более 100 л. Можно ли объехать всю дорогу в каком-либо направлении?

В ресторане, к 8 Марта 	Логические задачи  		Вес: 5 		Симпатии решивших: 89% 		06.03.2009
Пришла компания из N парней и N девчат отметить 8 Марта в ресторан. Посадили их неким случайным образом за большой вращающийся круглый стол. Официанту они заказали напитки, причем все парни заказали по кружке пива, а все девчата — по бокалу вина. Принеся заказ, официант все перепутал и расставил напитки случайным образом так, что большинство получило не свой напиток. Возмущению компании не было предела. «Не проблема, — сказал официант, — я смогу развернуть стол, не передвигая при этом напитки, таким образом, чтобы большинство из вас получили свой заказ». Всегда ли официант окажется прав?

Вписать треугольник 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 89% 		08.12.2010
Существует ли выпуклая плоская фигура, кроме круга, такая, что любой равносторонний треугольник со стороной 1 можно параллельным переносом вписать в нее? Треугольники отличаются ориентацией и положением центра на плоскости.

Сейф с алмазами 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 87% 		31.10.2009
Банковский сейф состоит из 200 ячеек. В трех из них хранятся алмазы: в первой ячейке — 35, во второй — 69, в третьей — 91 алмаз. Остальные ячейки пустые. Грабителю удалось проникнуть в банк и добраться до сейфа. Однако просто забрать алмазы нельзя: сейф стоит на сигнализации и, если поднимется тревога, грабителю несдобровать. Ему удалось частично заблокировать охранную систему и получить возможность, не вызывая тревоги, выполнять следующие операции: 1) переложить все алмазы из любой одной ячейки в любую другую; 2) переложить ровно половину алмазов из любой выбранной ячейки в любую другую; 3) забрать алмаз из любой ячейки, если он там один. Перечисленные операции можно выполнять неограниченное число раз и в любой последовательности. Сколько алмазов грабитель сможет украсть?

Шоколадка с ядовитой плиткой 	Игры  		Вес: 5 		Симпатии решивших: 86% 		20.04.2008
Дана шоколадка, состоящая из N×M плиток (причем плиток как минимум две), плитка в левом нижнем углу ядовитая. Двое по очереди отламывают куски шоколадки и съедают их. За каждый ход игрок выбирает одну из оставшихся плиток, отламывает и съедает ее и все плитки, расположенные не ниже и не левее выбранной. Тот, кто будет вынужден съесть ядовитую плитку, проигрывает. Докажите, что у первого есть выигрышная стратегия.

Лабиринт 	Логические задачи  		Вес: 5 		Симпатии решивших: 85% 		26.12.2009
Любимую собаку-киборга мегамозга злобные оккупанты посадили в клетчатый лабиринт 6х6 клеток, в левую нижнюю его клетку. В правой верхней клетке находится лестница - выход из лабиринта. Стороны квадрата: северная, восточная, южная и западная – непроходимы, также между некоторыми клетками стоят непроходимые перегородки, однако путь от собаки к выходу существует. Но Мегамозг все это предусмотрел и заранее снабдил собаку бесконечным источником энергии и конечной последовательностью команд, которую она начинает выполнять, попав в лабиринт. Собака понимает команды вида: «север», «юг», «запад», «восток». При выполнении команды она перемещается в соседнюю клетку в соответствующем направлении. Наткнувшись на перегородку, собака останавливается и переходит к выполнению следующей команды. Как мегамозг мог задать такую последовательность команд, выполняя которую, собака гарантировано когда-нибудь наткнется на выход?

Умножение на 4 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 84% 		04.06.2007
Найти все натуральные числа, которые при умножении на 4 превращаются в свое зеркальное отражение. (Зеркальное отражение — это когда цифры в нем идут в обратном порядке).

Раскраска бумаги 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 84% 		03.12.2011
Не отрывая карандаша от бумаги и не проходя по линии дважды, на плоскости нарисовали замкнутую кривую. Докажите, что образовавшиеся при этом области можно раскрасить в два цвета так, что никакие две смежные области не окажутся одноцветными.

Камни в урнах 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 84% 		10.12.2011
В ряд стоит бесконечное число урн, в которых могут лежать камни. Известно, что в урне с номером n+m лежит столько камней, сколько в урнах с номерами n и m в сумме, либо на один больше. В урне с номером 9999 лежит 3333 камня. Сколько камней в 2011-й урне?

Больше/меньше 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 84% 		02.01.2012
Оккупанты, известным только им образом, выбирают два различных вещественных числа и записывают их на двух бумажках. Затем предлагают Мегамозгу выбрать любую бумажку, посмотреть на написанное там число и угадать, больше число на другой бумажке или меньше. Докажите, что у Мегамозга есть стратегия, которая позволит ему угадать с вероятностью больше 50%.

Узники в коридоре 	Логические задачи  		Вес: 5 		Симпатии решивших: 83% 		15.02.2009
Мегамозг решил запереть трех узников в прямом коридоре, разделенном пятью проходами на шесть комнат, причем в каждом проходе, облокотившись на одну из стен, стоит толстый усатый стражник. Каждый раз, когда узник переходит из одной комнаты в другую, стражник, стоящий в этом проходе, переходит к противоположной стене и облокачивается на нее (если одновременно идут несколько узников, стражник переходит соответствующее число раз). Если все стражники облокотятся на одну стену, она не выдержит и рухнет, а узники выйдут на свободу. Может ли Мегамозг изначально так прислонить стражников и разместить узников, чтобы они никогда не смогли выбраться?

Герб 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 83% 		24.09.2010
На гербе одного древнего рода мегамозгов изображены четыре окружности одинакового радиуса: три красные и одна синяя. Причем любые две красных и синяя окружности пересекаются в одной точке. Докажите, что и все три красных окружности пересекаются в одной точке.

Очередь за спичками 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 82% 		02.08.2010
Сто мегамозгов стоят в очереди и хотят купить по коробку спичек по цене 50 коп. У 50 из них есть только по монете в 50 коп., а у других 50 есть только по монете в рубль. Найти вероятность, что продавец сможет выдать всем сдачу, если в начале в кассе денег нет.

Средний класс 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 82% 		06.03.2011
В Мозголяндии богатыми считаются люди, для которых существует расстояние R1, в радиусе которого они богаче большинства своих соседей. Бедными считаются люди, для которых существует расстояние R2, в радиусе которого они беднее большинства своих соседей. Средним классом в Мозголяндии называются люди, которых можно считать и богатыми, и бедными. Какой максимальный процент людей среднего класса может проживать в Мозголяндии?

Три события 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 81% 		03.07.2012
Есть три попарно независимых события, которые не могут произойти одновременно. Каково максимальное произведение их вероятностей?

Мегамозг и Оккупант-дальтоник 	Взвешивания  		Вес: 5 		Симпатии решивших: 80% 		16.03.2009
Мегамозг работал окулистом у Оккупанта-дальтоника. Оккупанту приснилось, что для того чтобы вернуть ему цвета жизни, Мегамозг должен изготовить 9 красных и 9 синих хрусталиков, на вид ничем не отличающихся друг от друга, кроме цвета. Хрусталики одного цвета весят одинаково, но красные легче синих. Мегамозг выполнил свою задачу и принес Оккупанту две кучки по 9 хрусталиков: в одной — все красные, в другой — все синие. Но Оккупант не доверяет Мегамозгу, а доверяет только показаниям чашечных весов без стрелки и гирь. Каким образом Мегамозг за три взвешивания может убедить Оккупанта, что в первой кучке все хрусталики красные, а во второй — все синие?

Клетки и квадраты 	Игры  		Вес: 5 		Симпатии решивших: 80% 		21.12.2009
На бесконечном листе клетчатой бумаги два Мегамозга играют в такую игру: первый по сетке рисует квадрат со сторонами 2 или 3, а второй закрашивает в этом квадрате одну клетку и так далее по очереди. Ни один из игроков не может повторять ранее сделанный ход. Второй выигрывает, если сможет сделать 15 ходов, иначе выигрывает первый. Кто победит при правильной игре обоих?

Брейнреслинг 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 79% 		20.07.2008
В одну из любимых игр мегамозгов, брейнреслинг, играют два игрока, и ничьих в ней не бывает. Однажды несколько (как минимум трое) мегамозгов устроили турнир по брейнреслингу по круговой системе (каждый играет с каждым). За победу игрок получает 1 балл, за поражение — 0 баллов. После подсчета своих рейтингов (сумм баллов) мегамозги решили посчитать еще и свои коэффициенты крутизны — суммы рейтингов тех соперников, которых победил каждый мегамозг. Коэффициенты крутизны у них оказались одинаковыми. Возможно ли, что их рейтинги не были одинаковыми?

Разрезание куба 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 78% 		10.02.2008
Можно ли куб разрезать на конечное количество кубиков меньшего размера так, чтобы все они были разными?

Коллекционер красивых камней 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 78% 		24.04.2008
Мегамозг коллекционировал разные камни и однажды нашел очень красивый экземпляр. Камень имел форму выпуклого многогранника и состоял из нескольких различных материалов. Всегда ли Мегамозг сможет положить такой камень на полку на одну из граней в устойчивом положении?

Подбросить мешок 	Физические задачи  		Вес: 5 		Симпатии решивших: 78% 		12.02.2012
На какую высоту подбросится мешок с песком массы 10кг с помощью легкой доски длиной 1м, если на другой конец доски с высоты 1м упадет такой же мешок с песком? Доска горизонтальна и опирается на клин, который делит ее в соотношении один к трем. Мешок падает на короткий конец доски. Высотой клина можно пренебречь. Столкновения абсолютно неупругие.

Опыт с весами 	Взвешивания  		Вес: 5 		Симпатии решивших: 77% 		26.08.2010
У Мегамозга есть набор из n+1 гирек общей массой 2n и чашечные весы. Он знает, что масса каждой гири натурaльное число. Однажды Мегамозг решил провести такой опыт: на каждом шаге, он брал самую тяжелую гирю из оставшихся и клал ее на более легкую в этот момент чашу весов. У него в конце весы оказались в равновесии. А могло ли быть иначе?

Иголки и многоугольники 	Логические задачи  		Вес: 5 		Симпатии решивших: 77% 		12.11.2011
На листе бумаги площадью 100 нарисовано 100 непересекающихся многоугольников площадью 1, а на его обратной стороне нарисовано еще 100 непересекающихся многоугольников площадью 1. Всегда ли можно воткнуть в лист 100 иголок так, чтобы в любой многоугольник втыкалась только одна?

Оккупанты и два мегамозга 	Логические задачи  		Вес: 5 		Симпатии решивших: 76% 		14.03.2008
Подлые оккупанты опять совершенно неожиданно захватили двух мегамозгов. Они приготовили 2 колпака, написали на одном из них число от 1 до 99, а на другом число на 1 большее (мегамозги об этом знали). Потом надели эти колпаки на захваченных и посадили их друг перед другом. Оккупанты по очереди спрашивают, знают ли мегамозги, какое число написано на их колпаке, пока кто-нибудь из них не ответит, но спрашивать будут не больше 231 раза. Их пустят на колбасу, если либо ответ окажется неверным, либо за 231 раз никто не ответит. Как мегамозгам выжить?

Четыре шара и цилиндр 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 76% 		19.02.2009
На бесконечной плоскости лежат 4 шара и 1 цилиндр, причем каждое из тел касается всех остальных. Цилиндр бесконечный в обе стороны. Радиус цилиндра равен 1. Требуется описать относительное расположение шаров и цилиндра, а также найти радиусы всех шаров.

«Данетка» 	Лжецы, хитрецы и правдивцы  		Вес: 5 		Симпатии решивших: 75% 		17.05.2007
Перед вами три шкатулки, в одной из которых находится конфета, и ведущий знает, в какой именно. Ведущий всегда говорит правду, но ответить может только на вопрос о ложности или истинности некоторого суждения «да» или «нет». Как узнать, где лежит конфета, задав ведущему всего один вопрос? Ответ ведущего строится по законам математической логики.

Юбилейный турнир 	Алгебра, математика  		Вес: 5 		Симпатии решивших: 75% 		26.05.2009
«На 40-летний юбилей города проходил футбольный турнир, — рассказывал Мегамозг своим внукам. — Участвовало пять команд. Каждая сыграла с каждой один матч. За победу в матче команда получала 3 очка, за ничью — 1, за проигрыш — ничего. При подведении итогов оказалось, что все команды набрали разное число очков, а всего было забито 40 мячей — столько же, сколько лет городу. Но обнаружилась еще одна удивительная закономерность: любая команда, занявшая более высокое место, в сумме забила голов меньше, а пропустила в свои ворота больше, чем любая команда, занявшая более низкое место». Могло ли такое быть или же пожилой Мегамозг что-то перепутал?

Угадайка 	Теория вероятностей  		Вес: 5 		Симпатии решивших: 75% 		26.01.2013
Мегамозг угадывает число, выбранное случайным образом из натуральных чисел от 1 до 2014. После каждого неверного варианта ему сообщают: перебор или недобор. Называть можно только те числа, которые еще не исключили. Мегамозг выигрывает, если угадывает число с нечётной попытки. Сможет ли Мегамозг выигрывать с вероятностью большей 2/3?

Карта рельефа 	Логические задачи  		Вес: 5 		Симпатии решивших: 74% 		27.11.2011
Рассматривая карту рельефа Мозголяндии, Мегамозг неожиданно подметил интересную особенность: средняя высота любых четырех точек, лежащих в вершинах одного квадрата, равна нулю. Верно ли, что Мозголяндия идеально плоская?

Кофе с пеной 	Физические задачи  		Вес: 5 		Симпатии решивших: 65% 		19.12.2007
Где соберется пена при размешивании кофе?

Часовой на мосту 	Геометрические задачи  		Вес: 5 		Симпатии решивших: 61% 		04.08.2008
Часовому было приказано ходить по одномерному мосту длиной 100 м в течение одного часа таким образом, чтобы побывать в каждой точке моста четное число раз (0, 2, 4 и т.д.). Стоять на месте и прыгать нельзя, т.к. мост заминирован и может взорваться. Начинать и заканчивать маршрут часовой может в любой точке моста по своему усмотрению. Сможет ли часовой придумать такой маршрут? Примечания: 1) скорость часового конечна, 2) разворачиваться часовой может мгновенно.
