* Подготовка солдата
Посмотри на дорогу, она зовет тебя, но выйди на нее - и она покажет тебе, кто ты есть.
* Формирование части
Элита есть элита. Корпус штурмовиков одним своим приближением может обратить в бегство противника.
* Битва
Необходимо собрать все части, имеющиеся в наличии.
* Story
** Персонажи
*** Инженеры
Повелители Гидр
Повелители Китов
Повелители Медведей
Повелители Драконов
*** Механики
*** Штурмовики
*** Гвардия Дворца
*** Рейнжеры
*** Волшебники
*** Мечники
**** Багряные нашивки
**** Железные сотни
*** Сверхтяжелая пехота
**** Черные черепахи
Огромные тяжелые черные доспехи. Щитов нет. 
Вооружение - тяжелые двуручные глефы, огромное лезвие, короткая рукоятка.
**** Огненные броненосцы
Красные наборные доспехи из толстых пластин. Вооружение - широкий высокий прямоугольный щит.
 Два железных ядра с порохом. 10 коротких тяжелых болтов. Булава.
*** Тяжелая конница

** Десятый Медведь
Только Десятый Медведь сможет вырвать для нас победу!
Мы больше не пытаемся создать Медведя. Командование Инженерным Корпусом переходит к Повелителю Гидр.
- Повелителю Гидр не собрать Медведя! - лицо Даниэля пылало, голос сорвался.
- Повелителю Медведей также не собрать Медведя.  Даниэль, я на твоей стороне. Но последние твои три Медведя развалились. Гипотеза о девяти Медведях не опровергнута и за последние два года никакие десять из найденных деревьев не создают идеальную конфигурацию для танка. Ты знаешь, что значит отсутствие идеальной конфигурации - в голосе Главного Инженера появился металл - это значит, что Медведь или не сдвинется с места или , что еще хуже, развалиться. При этом гибнут и теряют здоровье механики.
** Битва на Каменном Поле
Все десять Медведей готовы
** Пыльные свитки
Не пропали даром ночи, проведенные за пыльными свитками.  Семь лет Инженерной Академии сделали хрупкого юношу повелителем машин, сеющих ужас и смерть на полях сражений. Специальность Даниэля - огромные танки-медведи, сложенные из вековых дубов, скрепленных огромными цепями. Тяжело спроектировать такой танк, одна небольшая ошибка в расчетах - и громадина не сможет сдвинуться с места или с грохотом развалиться, круша строительные леса и как кегли раскидывая механиков, собирающих ее по чертежам инженера. Нет двух одинаковых деревьев в бескрайних лесах Империи, и потому каждый новый Медведь требует бесчисленных расчетов, прежде чем его создание станет возможным. Но кто видел, как на поле битвы деревянный монстр сминает бронированный клин тяжелой конницы Нарраса, знает - оно того стоит.
 Инженеры - настоящая элита армии. Их немного, но много жизней сохраняют созданные ими машины. За бронированными бортами Гидры не достанет морского пехотинца стрела эльфийского снайпера с Дальних Островов, сохранит жизнь рейнджеру его механический пес, вцепившись в горло горному тролю и  спокойно спят ночами жители городов Империи окруженных кольцами хитроумных защитных механизмов.
** Архимаг
Волшебство мое, волшебство. Яркие искорки, послушные движению ладоней. Вот грусть моя сделала вас темными, и воспоминания мои замедлили ваш бег. Складки парчового плаща сковывают движения и тяжелы шаги усталых ног. Узловатый посох с гулким стуком взбивает облачка пыли, опускаясь на изрезанную трещинами заброшенную дорогу. Только камни и пыль. Один на сотни тысяч локтей, и только сокол высоко в  небе наблюдает за фиолетовым,  расплывающимся в мареве полуденного солнца пятном, уныло плетущимся по дороге.
** Легат
   Разбойники достали из под плащей ножи. Легат подкинул в воздух мешочек и разноцветная вспышка озарила окрестность. В тот же момент ворота города открылись, и конница, как разноцветная река вошла в русло дороги. Следом тяжело громыхала пехота. Разбойники, что были ближе к легату, бросились назад в лагерь - бывшие в лагере переворачивали телеги, спешно сооружая защитную линию. Легат сжал поднятую руку в кулак - сейчас он отдаст приказ, и конница развеет разбойничий лагерь по полю, словно и не было его вовсе. Но тут случилось что- то очень странное. Рыцари правого крыла, должного выстроится в боевой порядок над оврагом, лишь на мгновение задержались на боевой позиции, после чего дружно развернули коней, и железной лавой, ощерившейся пиками, потекли в овраг. Этого просто не могло быть, конница столицы известна своей дисциплиной. Что может случиться такого, что заставит паладинов нарушить строй перед атакой? У легата засосало под ложечкой. Подав знак спешиться ближайшему всаднику, он вскочил на коня и во весь опор понесся к оврагу. Разбойники ошеломлено наблюдали, как вся бронированная масса всадников и пеших мечников развернулась к ним боком и бросилась в сторону оврага.
Легат вылетел на холм над оврагом, окинул взглядом склон и у него похолодело внутри. Личи. Неспешно паря над землей на высоте конника они подымались по склону, напевая свою не слышимую песню. Не похожие друг на друга, в прекрасных лиловых одеждах, но одинаково наводящии ужас. Но нет страха у паладина, есть только лютая ненависть, бросающая его при виде лича в атаку, часто последнюю. Внизу уже завязался бой. Высокий стройный лич в лиловых цилиндре и длинной мантии запрокинул голову и рот его стал похож на черную воронку, песня его стала слышимой, превратившись в тонкий, леденящий душу вой. Вой этот выдернул из седла нависшего над ним всадника и закинул его далеко за спину личу. Палаш второго всадника завернулся штопором, и вывернув ему правое плечо, выпал из руки. Развернув коня, в диком оскале, рыцарь левой рукой выхватил из седельной сумки булаву и в страшном ударе обрушил ее на цилиндр. Цилиндр с треском лопнул и облако лиловой пыли окутало всадника и коня. Легат отвернулся, он знал, что будет дальше, и не хотел этого видеть. В двадцати шагах от него по склону плавно поднималась бледная дама с уложенными в изысканную прическу волосами и бездонными провалами агатово-черных глаз. Ведьма пятого уровня по виду.
** Архимаг, инженер
Волшебник устало улыбнулся. -Рыцарь, будь вежлив. Это само по себе не плохое свойство, кроме того ты не знаешь, кто сидит перед тобой. Гвардеец захохотал. Смех его звучал, словно груда булыжников, прокатившихся по жестяной кровле. Он приподнялся на кулаках над столом и налитыми кровью глазами уставился в переносицу старику. - Вежливость - удел слабых и паладинов! Ты старая развалина, как смеешь указывать мне, как себя вести. Инженер видел, чародей был в опасном положении. Мечник был агрессивен и здоров, как матерый бугай. Кроме того доза алкоголя сделала свое дело, отключив остатки и так не очень развитого ума. В Штурмовую Бригаду Гвардии Дворца набирают конечно не по результатам тестов по математике. Инженер на ватных ногах направился к столу. Проклятый противный холод внизу желудка мешал сосредоточиться. -Так, дышим ровно, мысли приводим в порядок- это про себя. Теперь вслух, словно нырнул в холодный поток - Оставь старика в покое! Гигант медленно повернул маленькую голову на толстой шее и удивленно уставился на Даниэля. Глаза удивленно оглядывали стройную тонкую фигуру в коричневой мантии. Это еще что за сморчок? - Жить надоело? - радостно поинтересовался рыцарь. -Сложно-организованные организмы находятся на расстоянии от небытия, не позволяющем адекватно сформулировать желание прекратить свое существование.- сразу ответил Даниэль, внимательно изучая стальные носки сапог рыцаря. Челюсть штурмовика медленно перешла в максимально нижнее положение. Ошалело посмотрев на молодого человека, потом на старика, потом почему-то на камин, потом опять на Даниэля, рыцарь пинком отбросил тяжелую дубовую скамью, громко и смачно выругался и ,грохнув дверью, медведем вывалился из трактира.  - У штурмовиков молниеносные рефлексы, а для создания заклинания нужно минимум десять отсчетов. - почему-то оправдываясь обратился к старику Даниэль. - Не для архимага, молодой человек - улыбка покрыла лицо чародея причудливой сетью морщинок, словно тень таинственной карты с множеством дорог отпечаталась на нем. Архимаг провел рукой, и скамья, опрокинутая рыцарем, плавно повернувшись в воздухе, возвратилась на место. - Садитесь, юноша, скоротаем вечер за приятной беседой.
** Штурмовики
Храбрость штурмовиков общеизвестна. Это не бесстрашие паладинов, озаренное ослепительным внутренним пламенем, бушующем в сердце каждого рыцаря Храма. Не осторожная смелость рейнджера, никогда не опускающего глаз перед ужасом неизвестного. И не безумие берсерка, теряющего рассудок и превращающегося в дикого зверя, остервенело кидающегося на врага. Штурмовик бросается в бой, как умелый пловец в бурную реку. Отчаянная рубка - его стихия, в ней он дома, другого у него нет. Вне ее он беспокоен и груб, буян и задира, но музыка стали, со свистом рассекающей воздух, делает взгляд его ясным, а дух спокойным - здесь он на своем месте.
** Дворцовая Гвардия. Боевое крещение
Сквозь туман были видны холмы. По ним колоннами спускались темные фигурки. Светлое от инея поле темнело, словно заполняясь черной зимней водой. Сотник зябко повел закованными в сталь плечами и оглянулся на свой одетый в сверкающую броню отряд. Взгляд его пробежал по сомкнутой стене щитов, задержался на узкой прорези шлема ближайшего латника. Воин смотрел на него спокойным выжидающим взглядом. Гвардия Дворца - закаленные изнурительными тренировками бойцы, облаченные в выкованные искусными кузнецами доспехи, с темным гербом короля на отливающей синевой стали левого нагрудника. Словно с картинок дорогих книг сошедшие рыцари - цвет страны. Не разу не бывшие в настоящем бою. Сотник резко отвернулся и до боли сжал рукоять меча.  Закрыв глаза, он вспоминал путь, приведший его на это поле. Суровый ветеран, в походах против варваров Востока заслуживший Звезду Мужества, намертво прикрученную к его латам в память о девяноста мечниках из его сотни, оставшихся навечно лежать у ворот угрюмого  города Наррасс - столицы империи Лерр. В этой рубке он стал сотником, вместо предыдущего командира, разрубленного надвое огромным двуручным топором минотавра из личной охраны Верховного Лорда Наррасса. За пример, поданный при штурме, сотня была отмечена правом носить багряные нашивки на плащах и была спешно доукомплектована победителями общевойсковых соревнований фехтовальщиков пехотных полков. Покрыв себя славой в дальнейшей кампании и заслужив статус Железной, сотня в полном составе полегла на Дальних Островах в битве на Каменном Поле. Дубина тролля вбила сотника в землю, откуда на следующее утро его извлекли санитарные части. Из трехтысячной пехотной ударной линии в живых остался он один. С множеством переломов, тяжелым сотрясением головы и ушибом внутренних органов сотник месяц провалялся в госпитале, что скорее всего и позволило ему остался в живых на тот момент. В этой кампании Империя поставила на колени дикарей Дальних Островов ценой потери 90 процентов личного состава Восточной Армии. Империя не забыла героя-рубаку и выйдя из госпиталя он возглавил  сотню мечников Дворцовой Гвардии, элитного корпуса имперских войск.
** Мечник, орк
Тяжело звенело в ушах, глаза заливало потом. Мечник прижимал к себе щит, покрытый вмятинами, устало следя за противником в прорезь изуродованного тяжелыми ударами шлема. Тяжелый выдох со свистом вырвался из спекшихся губ, превратившись в холодном воздухе в облачко пара. Вложив в прыжок всю массу тела, человек обрушил меч на голову орка. Усталость сделала удар неточным - меч сбил рог со шлема и со звоном отскочил от шипастого наплечника, вырвавшись из рук.
