-*- coding: cp1251 -*-
* Метрики. p-адический анализ (3 пары)
Возможность использования разнообразных метрик позволяет гибко применять инструментарий математического анализа в широком круге решаемых задач. Специфика решаемой задачи мотивирует использование той или иной метрики - метрика Хэмминга в кодировании, использование минимального геодезического расстояния в геометрии поверхностей, ультраметрики в теории графов и конечных автоматов. Рассмотрение конструкций p-адического анализа иллюстрирует применение нестандартной метрики. Демонстрируется использование  ультраметрики и p-адического анализа в теории конечных автоматов.
** План
*** Лекция 1 
Определение понятия расстояния.
Примеры метрик, применение
Основы анализа в метрических пространствах.
Непрерывность, сходимость в разных метриках. 

Lecture 1
The definition of distance.
Examples of metrics used
Fundamentals of analysis in metric spaces.
The continuity, the convergence of different metrics.

*** Лекция 2
Ультраметрика. Определение.
Метрические свойства пространств с ультраметрикой.
Сходимость в ультраметрике.
Замыкание множества натуральных чисел в метрике Бэра.

Lecture 2
Ultrametric. Definition.
Metric properties of ultrametric spaces.
The convergence in ultrametric.
The closure of the set of natural numbers in the Ber's metric .

*** Лекция 3
Кольцо целых p-адических чисел.
Основы p-адического анализа.
Конечные автоматы. Определение.
Применение p-адического анализа в теории групповых автоматов.

Lecture 3
The ring of p-adic numbers.
The basic of p-adic analysis.
Finite state machines. Definition.
The use of p-adic analysis in the theory of group's automatous.
* Теорема Геделя (4-5 пар)
Понимание теоремы Геделя нужно для того, что бы программист имел понятие о границах применимости. Кроме того, доказательство этой теоремы - 
хороший пример формализации. Умение же правильно формализовать поставленную задачу является ключом к эффективной оптимизации. 
Оптимизация начинается тогда, когда мы можем что-то формализовать, когда мы можем сформулировать задачу настолько точно, что можно построить алгоритм. Разбор теорем математической логики является эффективной тренировкой практики построения алгоритмов и важной составляющей при построении моделей поставленных задач. 
* Мотивация проведения треннигов
В течении моей работы в Самсунге к моему рабочему месту регулярно подходят вдумчивые молодые люди с грустными глазами. Проведя статистический анализ нашего полного глубокого смысла общения я пришел к неожиданному и ошеломляющему выводу - информационный голод негативно влияет на обмен веществ в организме и является причиной различного рода стрессов и психических расстройств. Я оказался перед непростым выбором - отнестись ли к данной проблемме поверхностно, сославшись на пятый закон термодинамики и смирившись с неизбежным увеличением энтропии во вселенной или протянуть мозолистую руку помощи труженника-математика. Мог ли я оставаться в стороне, имея в своем распоряжении целебный эликсир p-адического анализа и прохладный бальзам формальной логики, успокаивающий взалкавшие знаний души? Нет и еще раз нет! Страждующие, помощь близка, ничто не остановит меня и не собьет с тернистой стези добрых дел.
 Уважающий знание и доброкачественные(не использующие темной магии) фокусы, Математик.
